global:
  scrape_interval: 5s

# 1. Le decimos a Prometheus que lea nuestro nuevo archivo de alertas
rule_files:
  - "alerts.yml"

# 2. Le decimos a dónde enviar la alerta cuando se dispare
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'veterinaria_php'
    metrics_path: '/veterinaria/index.php/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:80']